### ISSUE TITLE
Straight or curved lines in Figs. 7 and 9?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#38]
Markus made two versions of figures 7 and 9. Other ones has all the data points joint by lines;
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/cholesterolization_lp.pdf
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/dehydration_lp.pdf

the other ones shows smooth trend lines (cubic polynomials) to ease qualitative comparison. 
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/cholesterolization_smooth.pdf
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/dehydration_smooth.pdf

I think that the straight line plots are better, Markus thinks that smoothed plot is better. We have to decide which one to use. Do others have opinions?

**Comment by HubLot** [comment]
First, in the cholesterol smooth figures, there are missing lines for g2, g1R and g1S for (I think) the charmm36 298K. For alpha, beta and g3, the 2 lines for the 2 charmm36 have the same type (plain line) making very hard to distinguish the 2 set of data. Maybe setting the line related to empty dots (298K CHARMM36) dashed (--) will improve that.

Overall, in my humble opinion, I think it's more difficult to read the figure with the smooth lines. Since not all the lines reached the dots, this add another information inside a crowded plot.

**Comment by markussmiettinen** [comment]
Thanks for the comments Hubert!

Let me clarify that there are **no missing lines** in the smooth figures. However, there are fewer lines, because for describing a given C-H order parameter, only one trend line is shown. That is, for example in alpha-C of CHARMM36 for which we have two data sets, the two lines shown are for the two hydrogens connected to the alpha-C. In fact, one of my main reasons for creating the figure with the trend lines was to cut down the number of lines.

Anyhow, the current vote is **2-3**. For smooth: Markus and Patrick, for joint: Samuli, Tomek, Hubert.

**Comment by HubLot** [comment]
> Let me clarify that there are no missing lines in the smooth figures. However, there are fewer lines, because for describing a given C-H order parameter, only one trend line is shown. That is, for example in alpha-C of CHARMM36 for which we have two data sets, the two lines shown are for the two hydrogens connected to the alpha-C. In fact, one of my main reasons for creating the figure with the trend lines was to cut down the number of lines.

Ohh indeed, I missed read the figure and didn't realized the fewer lines across all subplots. So, if I understood well, from the 2 data sets of CHARMM36, you made only 1 trend line?

**Comment by markussmiettinen** [comment]
Yes, you understood correctly. The same applies to the 2 data sets of experimental data: A single trend line is enough to guide the eye (in my opinion).

**Comment by ffavelar** [comment]
Straight line plots.

**Comment by markussmiettinen** [comment]
Current standings: **3 - 4**

Smooth: Markus, Patrick, Matti
Joint: Samuli, Tomek, Hubert, Fernando

**Comment by lucamonticelli** [comment]
I vote for the straight lines.
L

**Comment by markussmiettinen** [comment]
Current standings: **4 - 7**

Smooth: Markus, Patrick, Matti, Matej
Joint: Samuli, Tomek, Hubert, Fernando, Luca, Alexandru, Jukka

**Comment by markussmiettinen** [comment]
The voting is closed. Straight lines were chosen.
